name: MODULE White Paper
author: MODULE
baseurl: /
description: Cryptoeconomic ecosystem on a decentralized file storage network.
github: https://github.com/module-project/
twitter: https://twitter.com/MODULE_Project
facebook: https://www.facebook.com/moduleproject/
linkedin: https://www.linkedin.com/company/module-mdl/
email: modlsupport[at]modltoken.io
location: 22°17'58.3"N   114°10'04.5"E
disqus: modl_admin

##Make sure to edit the above fields, especially for disqus.


highlighter: rouge
redcarpet:
  extensions: ["tables"]

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
